name = "my-worker"
main = "src/index.ts"
compatibility_date = "2024-11-28"
name = "D1worker"
type = "javascript"

[env.production]
workers_dev = true

[env.production.kv_namespaces]
[[env.production.d1_databases]]
binding = "MY_D1_DB"  # The name of your binding (can be anything you like)
database_name = "982a4e65-bb8a-452b-8a55-78baeef4f47f"
